STACK	SEGMENT PARA STACK 'STACK'
	DW 20 DUP (?)
STACK	ENDS

DATA	SEGMENT PARA 'DATA'

DIGITS DB 0F9H,0A4H,0B0H,099H

DATA	ENDS

CODE    SEGMENT PUBLIC 'CODE'
        ASSUME CS:CODE, DS:DATA, SS:STACK
START:	
	MOV AX,DATA
	MOV DS, AX
	MOV AX, 90H
	MOV DX,306H
	OUT DX, AX	; CONTROL WORD'Ü AYARLAMA
	
RESET:
	MOV AX,0C0H
	MOV DX,302H
	OUT DX,AX
	XOR SI,SI	; DISPLAY RESETLEME
	
ENDLESS:
	MOV DX,300H	; A PORTUNUN ADRESİ
	IN AX,DX	; A PORTUNDAN BUTON VERİSİ OKUMA
	CMP AX,0FEH	; BASILAN BUTON RESET BUTONU MU
	JE RESET	
	CMP AX,0EFH	; BASILAN BUTON ARTTIRMA BUTONU MU
	JNE ENDLESS
	MOV DX,302H	; B PORTUNUN ADRESİ
	CMP SI,04H	; DİZİNİN SONUNA GELİNMİŞ Mİ
	JNE DISP	
	XOR SI, SI	
DISP:	MOV AL, DIGITS[SI]	
	OUT DX,AL	; B PORTUNA YAZDIRILACAK SAYININ DISPLAY DEĞERİ ÇIKILIYOR
	MOV DX,300H	
	IN AX,DX	; A PORTUNDA TUŞA BASILMAYA DEVAM EDİLİYORSA DISPLAYDEKİ DEĞER KALIYOR
	CMP AX,0EEH
	JNE DISP
	INC SI	
        JMP ENDLESS
	
CODE    ENDS
        END START
