;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;---------5.LAB 4.DENEY ----------- 18011052 ------------- FARUK VELİ ÖZDEMİR----------

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
STACK    SEGMENT PARA STACK 'STACK'
        DW 20 DUP(?)
STACK    ENDS

DATA    SEGMENT PARA 'DATA'
GIRIS	DW 'F','a','r','u','k',' ','V','e','l','i',' ','O','z','d','e','m','i','r',0DH
BILGI	DW 'I','N','P','U','T',' ','S','T','R','I','N','G',' ',' ',' ',' ',' ',' ',0DH
STRING	DW 19
ARRAY	DB 5 DUP(?)
IDX	DW 0
DATA    ENDS

CODE    SEGMENT PARA 'CODE'
        ASSUME CS:CODE, DS:DATA, SS:STACK
	
MAIN	PROC FAR
	PUSH DS
	XOR AX,AX
	PUSH AX
	MOV AX,DATA
	MOV DS,AX
	
	XOR AX,AX
	MOV ES,AX
	;RECEIVE VE TRANSMIT KESMELERİNİ KESME VEKTÖR TABLOSUNA YERLEŞTİRİYORUZ
	MOV AX, 78H				
	MOV BX, 4H
	MUL BX
	MOV BX,AX
	LEA AX, RECEIVE
	MOV WORD PTR ES:[BX],AX
	MOV AX, CS
	MOV WORD PTR ES:[BX+2], AX
	LEA AX, TRANSMIT
	MOV WORD PTR ES:[BX+4], AX
	MOV AX, CS
	MOV WORD PTR ES:[BX+6], AX
	

	;8251'i VERİ OKUMAK VE YAZMAK ÜZERE AYARLIYORUZ (8251 300H ADRESİNDE KONUMLANDIRILMIŞ)
	MOV DX, 0302H
	MOV AL, 01001101B
	OUT DX, AL			;MOD REGISTER
	MOV AL, 40H
	OUT DX, AL			;CONTROL REGISTER - RESET
	MOV AL, 01001101B
	OUT DX, AL			;MOD REGISTER AGAIN
	MOV AL, 00010101B		;CONTROL REGISTER FOR READ&WRITE
	OUT DX, AL
	
	;8259 AYARLAMA (8259 304H ADRESİNDE KONUMLANDIRILMIŞ)
	MOV DX, 0304H			
	MOV AL, 00010011B
	OUT DX, AL
	MOV DX, 306H
	MOV AL, 01111000B
	OUT DX, AL
	MOV AL, 00000011B
	OUT DX,AL
	STI
	
	LEA SI,GIRIS
	CALL YAZ
	LEA SI,BILGI
	CALL YAZ
ENDLESS:

	JMP ENDLESS

	RET
MAIN	ENDP	

YAZ	PROC NEAR		;BİLGİ MESAJLARINI EKRANA YAZDIRAN FONKSİYON
	PUSH CX
	MOV CX,STRING
L1:	MOV AX,[SI]
	PUSH AX
	CALL TxRDY
	POP AX
	MOV DX,300H
	OUT DX,AX
	ADD SI,2
	LOOP L1
	POP CX
	RET
YAZ	ENDP


RECEIVE	PROC FAR 		;SANAL TERMİNALDEN GELEN HER SİNYALLE TEİKLENİP GİRİLEN KARAKTERİN BİR FAZLASINI DİZİYE ALAN İNTERRUPT
	PUSH BX
	PUSH SI
	
	MOV DX, 0300H		;SANAL TERMİNALDEKİ VERİ ALINDI
	IN AX, DX
	SHR AX,1
	PUSH AX			
	
	CALL TxRDY		;GİRİLEN DEĞER SANAL TERMİNALDE TEKRAR GÖSTERİLİYOR
	POP AX
	MOV DX,300H
	OUT DX,AX
	
	INC AX			;GİRİLEN DEĞER BİR ARTTIRILIYOR VE DİZİYE ATILIYOR
	MOV SI, IDX		;SIRADAKİ INDIS DEĞERİ SI'YA ALINIYOR
	MOV ARRAY[SI],AL
	INC IDX			;İNDİS DEĞERİ BİR ARTTIRILIYOR 
	
	CMP IDX,5		;5 TANE KARAKTER GİRİLDİĞİ ANDA YAZDIRMA INTERRUPTI TETİKLENİYOR
	JNE L1
L2:	INT 79H
		  
	LEA SI,BILGI		;EKRANA BİLGİ YAZDIRILIYOR
	CALL YAZ
L1:	
	POP SI
	POP BX
	IRET
RECEIVE	ENDP	
	
	
TRANSMIT PROC FAR		;5 TANE KARAKTER GİRİNCE TETİKLENEN VE EKARAN GİRİLEN DEĞERLERİN BİR FAZLASINI YAZDIRAN INTERRUPT
	 PUSH SI
	 PUSH CX
	 XOR SI,SI
	 MOV CX,IDX		;DİZİNİN BOYUTU CX REGISTERINA ALINDI
	 
	 MOV AX,0DH		;ALT SATIRA GEÇMEK İÇİN TERMİNALE ENTER(0DH) YAZDIRILDI
	 PUSH AX
	 CALL TxRDY
	 POP AX
	 MOV DX,300H
	 OUT DX, AX
	 
L1:	 MOV AL,ARRAY[SI]	;5 KARAKTERLİK DİZİ EKRANA YAZDIRILIYOR
	 PUSH AX
	 CALL TxRDY
	 POP AX
	 MOV DX,300H
	 OUT DX,AX
	 INC SI
	 LOOP L1
	 
	 MOV AX,0DH		;TEKRAR ALT SATIRA GEÇMEK İÇİN TERMİNALE ENTER(0DH) YAZDIRILIYOR
	 PUSH AX
	 CALL TxRDY
	 POP AX
	 MOV DX,300H
	 OUT DX, AX
	 
	 MOV IDX,0		;INDEX DEĞERİ 0'LANIYOR
	 POP CX
	 POP SI
	 IRET
TRANSMIT ENDP
		
	
RxRDY	PROC NEAR   		;CHECK RxRDY PIN IS LOGIC 1 FOR RECIEVE DATA
    MOV DX, 0302H
TEKRAR:
    IN AL, DX
    AND AL, 02H
    JZ TEKRAR
    RET
RxRDY	ENDP       


TxRDY	PROC NEAR		;CHECK TxRDY PIN IS LOGIC 1 FOR TRANSMIT DATA
    MOV DX, 0302H		
TEKRAR:
    IN AL, DX
    AND AL, 01H
    JZ TEKRAR	
    RET
TxRDY ENDP   
	
CODE    ENDS
        END MAIN